### ISSUE TITLE
Issue with bootstrap-sass-extras

### ISSUE THREAD

**Issue by ljnissen** [doabit/bootstrap-sass-extras#17]
I'm using a very simple setup only to try this out. I'm developing on an 
old Windows 7 laptop, and the normal sass-rails design looks fine, but 
when I run sass-rails-extras with:

rails g bootstrap:install

followed by:

rails g bootstrap:layout application fixed

and then:

rails g scaffold Gonzo title:string body:text
rake db:migrate
rails g bootstrap:themed Gonzos

the layout does not render the way it's supposed to. The side-bar and 
header links are there but they show up in a big column instead of as 
proper headers and side-bars.

What am I missing?
 
I'm using => 'rails', '4.2.0', 
                    'ruby 1.9.3p545',
                    'sass-rails', '~> 5.0',
                    'bootstrap-sass, 3.3.4.1',
                    'bootstrap-sass-extras, 0.0.6'

**Comment by doabit** [comment]
Sorry, i haven't use the gem, i think https://github.com/Fullscreen/bh is a good choice.

**Comment by ljnissen** [comment]
It looks exactly the way that I want! Thank you!
