### ISSUE TITLE
Issue with loading of engine helpers

### ISSUE THREAD

**Issue by jh125486** [doabit/bootstrap-sass-extras#24]
Anyone else have a problem with helpers loading through the engine?
I'm running a fresh Rails `4.2.4` app with bootstrap-sass-extras `0.0.6`.

In a partial view:
```
= tabs do
      = nav_to 'Test1', '#'
      = nav_to 'Test2', '#'
```
I'm getting `undefined method `tabs' for #<#<Class:0x007fa2922eea28>:0x007fa2922edf10>`

Any ideas why the engine isn't getting the helpers to the ActionController?

**Comment by doabit** [comment]
Sorry, it should 
```ruby
= nav do
    = nav_to 'Test1', '#'
    = nav_to 'Test2', '#'
```

**Comment by jh125486** [comment]
Still getting `ActionView::Template::Error (undefined method 'nav' for #<#<Class:0x007ff7d0024e08>:0x007ff7d125df20>):`

Very odd.

No worries though, must be a weird class loading issue somewhere.

**Comment by mintuhouse** [comment]
Even I am facing same issue. Do you remember how you resolved it?

**Comment by doabit** [comment]
@mintuhouse I've released new version.

**Comment by mintuhouse** [comment]
Thankyou :+1:
