### ISSUE TITLE
Haml and Slim supported ?

### ISSUE THREAD

**Issue by jvenezia** [doabit/bootstrap-sass-extras#25]
How do we choose the template engine ?

This does not work for me : 
`rails g bootstrap:layout --template-engine=haml application`

**Comment by doabit** [comment]
@jvenezia If you haved added 'haml-rails' in `Gemfile`, run `rails g bootstrap:layout application` should work.
![4b1260cf-15e2-43db-b38c-19caecaf6675](https://cloud.githubusercontent.com/assets/330368/11957892/70c576fa-a8ff-11e5-90dc-932225eb4db5.png)

**Comment by jvenezia** [comment]
Thanks @doabit . I was using the 'haml' gem, not the 'haml-rails' gem.
