### ISSUE TITLE
Requirements? gem 'bootstrap-sass' or gem 'bootstrap', '~> 4.0.0.alpha4'

### ISSUE THREAD

**Issue by yoshie902a** [doabit/bootstrap-sass-extras#28]
Do I need either of theses gems for bootstrap-sass-extras to load boostrap?

gem 'bootstrap-sass' 
or 
gem 'bootstrap', '~> 4.0.0.alpha4'

**Comment by doabit** [comment]
`gem 'bootstrap-sass' `
