### ISSUE TITLE
undefined method before_filter

### ISSUE THREAD

**Issue by scottbarrow** [doabit/bootstrap-sass-extras#35]
This issue was resolved by https://github.com/doabit/bootstrap-sass-extras/commit/fda41b07e57de70b04ffece5aeafab68a7742d2d

However, if I use `gem 'bootstrap-sass-extras'` the update above is not present
If I use the git source and branch master It works locally but when I deploy I get an error
`You are trying to install in deployment mode after changing your Gemfile` relating to bootstrap-sass-extras

**Gemfile**
gem 'bootstrap-sass-extras', git: 'https://github.com/doabit/bootstrap-sass-extras.git', branch: 'master'

**Gemfile.lock**
GIT
  remote: https://github.com/doabit/bootstrap-sass-extras.git
  revision: 6aa549b91a66055a5f5e37400dbe44f4d17f09c3
  branch: master
  specs:
    bootstrap-sass-extras (0.0.7)
      rails (>= 3.1.0)

**Comment by doabit** [comment]
After change Gemfile, you must to  run `bundle install` to update Gemfile.lock

**Comment by scottbarrow** [comment]
Thanks, Im aware of that, I actually resolved this by specifying a git source at the head of the Gemfile
